---
apiVersion: v1
kind: services 
metadata:
  name: postgres-service
  labels:
    name: postgres-service
    author: intelliqit
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector: 
   name: postgres-pod
   app: demo-voting-app
