---
apiVersion: v1 
kind: Pod 
metadata:
  name: nginx
  labels:
   type: proxy
   author: intelliqit
spec:
 containers:
   - name: webserver
     image: mynginx
     ports:
      - containerPort: 80
        hostPort: 8080
