---
apiVersion: v1
kind: service 
metadata:
  name: redis-service
  labels:
    name: redis-service
    author: intelliqit
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
   name: redis-pod
   app: demo-voting-app
