---
version: '3'
services:
 voting-app:
  image: dockersamples/examplevotingapp_vote
  ports:
   - 6060:80
  redis:
   image:  redis
   ports:
    - 6379:6379
  worker-app:
   image: dockersamples/examplevotingapp_worker
  postgres:
   image: postgres
   environment:
    POSTGRES_PASSWORD: intelliqit
    POSTGRES_USER: myuser 
    POSTGRES_DB_: mydb 
   ports:
    - 5432:5432
  result-app: 
   image: dockersamples/examplevotingapp_result
   ports:
    - 7070:80
    